### ISSUE TITLE
expected   "Symplify\MonorepoBuilder\Release\Contract\ReleaseWorker\ReleaseWorkerInterface". 

### ISSUE THREAD

**Issue by tacman** [symplify/monorepo-builder#21]
I'm stuck on this error, and even after re-installing the recipe and even the whole bundle I still get the error.

I'm pretty much using this right out of the box, nothing special.  I suspect something is out of date, but I can't tell what.

 [ERROR] Expected an instance of this class or to this class among its parents                                          
         "Symplify\MonorepoBuilder\Release\Contract\ReleaseWorker\ReleaseWorkerInterface". Got:                         
         "Symplify\MonorepoBuilder\Release\ReleaseWorker\SetCurrentMutualConflictsReleaseWorker"

**Comment by tacman** [comment]
I deleted the reference to that file in monorepo-builder.php, but I'm leaving this open in case it's something that needs to be fixed.

**Comment by TomasVotruba** [comment]
The solution is simple. Remove the `SetCurrentMutualConflictsReleaseWorker`, as no longer part of worker set. It didn't serve well.
