### ISSUE TITLE
Forcing release workers by default might not suit every use case

### ISSUE THREAD

**Issue by tobalsan** [symplify/monorepo-builder#24]
Hi Tomas

in a recent update, the `PushTagReleaseWorker` and `TagVersionReleaseWorker` release workers [are now always included by default](https://github.com/symplify/monorepo-builder/commit/593d6c2a775450a6bec0dbf4284a7eabf9b73084#diff-f55db4bc294bbb90108ccfcbdd11881f4707473ad9384b382e2a6b653e118471R79) in the release process. 

In our company, we have a custom release process which requires us to create custom release workers, two of them that fill the role of the default release workers, amongst other things. 
It was working well prior the update, but now the two default release worker try to do their thing, which causes some conflict (one of our release workers takes care of creating the local tag, which the `TagVersionReleaseWorker` also tries to do).

What would be the most elegant way to disable this behavior?

Thanks for your help.

**Comment by ambroisemaupate** [comment]
Hi 

I have a similar issue. I'm using *git-flow* to create releases and I need to perform all release workers except `Push` and `Tag`, which are actually handled by `git flow release finish xxxx` command.

Thanks

**Comment by TomasVotruba** [comment]
Thank you for feedback, this makes sense to revert then :+1: 

Could you send PR?

**Comment by ambroisemaupate** [comment]
It is the same issue on https://github.com/symplify/symplify-kernel package.

```php
# src/Kernel/MonorepoBuilderKernel.php
// Always prepend default config files
$configFiles = array_merge(
    [
        ConsoleColorDiffConfig::FILE_PATH,
        __DIR__ . '/../../config/config.php',
    ],
    $configFiles,
);
```


```php
# vendor/symplify/symplify-kernel/src/HttpKernel/AbstractSymplifyKernel.php
// Always prepend default config files
$configFiles = array_merge(
  [
      SymplifyKernelConfig::FILE_PATH,
  ],
  $configFiles,
);
```

**Comment by TomasVotruba** [comment]
That seems like playing with Symfony magic.
Instead, those default workes should be removed.

**Comment by ambroisemaupate** [comment]
@TomasVotruba I don't understand what do you mean by 
> those default workes should be removed

For the moment, configuration order does matter because we cannot override default release workers or excluded folders defined in https://github.com/symplify/monorepo-builder/blob/main/config/config.php

**Comment by TomasVotruba** [comment]
Then it seems there are 2 separate issues. This one is about default registered workers.
