### ISSUE TITLE
symfony/console:^6.2 dependency incompatible with LTS versions of Adobe Commerce

### ISSUE THREAD

**Issue by AntonEvers** [symplify/monorepo-builder#29]
Hi @TomasVotruba,

I see that you have a dependency on symfony/console:^6.2 and I am wondering if there is any specific reason that only this version is required. Adobe Commerce requires symfony/console:~4.4.0 in some LTS versions and symfony/console: ^5.4 in the most recent. It would be great if symplify/monorepo-builder could work with symfony/console 4 and 5 as well. What is needed to test whether the program works with symfony/console 4 and 5 and can we work towards including them in the dependencies?

As an alternative, we could think about also publishing a monorepo-builder-dist version of the package, similar to https://github.com/netz98/n98-magerun2-dist which is a phar version of https://github.com/netz98/n98-magerun2. This would bundle all dependencies of the monorepo-builer into the phar and remove the dependency conflicts.

What are your thoughts?

**Comment by TomasVotruba** [comment]
Hi,

this package is downgraded to PHP 7.2 and scoped from all the dependencies, so no conflict is possible.

See: https://packagist.org/packages/symplify/monorepo-builder#11.2.2.72

**Comment by AntonEvers** [comment]
Ah so this only happens when I require dev-main and should never happen when a stable version is required, correct?

**Comment by TomasVotruba** [comment]
Exactly :) the `dev-main` should never be used here.
