### ISSUE TITLE
Requesting a new release for this package

### ISSUE THREAD

**Issue by AntonEvers** [symplify/monorepo-builder#31]
Hi @TomasVotruba,

In order to use the latest additions in my recent pull requests, I am waiting for a new release of monorepo-builder.
Can you please build a new version so that I can start using the newest additions in my projects?

**Comment by AntonEvers** [comment]
@TomasVotruba kind reminder for this request

**Comment by TomasVotruba** [comment]
There you go https://github.com/symplify/monorepo-builder/releases/tag/11.2.3

Thanks for you patience :pray:
