### ISSUE TITLE
init throws error

### ISSUE THREAD

**Issue by JRoblesAtQuadrant** [symplify/monorepo-builder#63]
[ERROR] Could not resolve argument "Symplify\MonorepoBuilder\Config\MBConfig $mbConfig"

Error not happening with 11.2.14.*

**Comment by juliangut** [comment]
Experiencing the same problem here, previous version 11.2.17 did not have the problem

**Comment by kayw-geek** [comment]
This problem is because the downgraded job fails due to the `DowngradeUnionTypeDeclarationRector` rule error of rector. I will find a way to solve it. You can return version 11.2.17 first.

**Comment by kayw-geek** [comment]
@TomasVotruba I checked the failed job in the action, which may be caused by this `DowngradeUnionTypeDeclarationRector` rule of Rector. Do you know the reason?

**Comment by kayw-geek** [comment]
@jdreesen @JRoblesAtQuadrant 
The issue has been fixed on latest version 11.2.19, using the `composer update --with symplify/monorepo-builder:11.2.19
` command to enjoy it.

**Comment by JRoblesAtQuadrant** [comment]
Thanks a lot!
